extends: base.yaml

tornado:
  autoreload: true

timedelta:
  port: 80

logging:
  version: 1
  formatters:
    simpleFormater:
      format: '%(asctime)s - %(levelname)s: %(message)s'
      datefmt: '%Y/%m/%d %H:%M:%S'
  handlers:
    file:
      class: logging.FileHandler
      formatter: simpleFormater
      level: DEBUG
      filename: /var/log/timedelta.log
    console:
      class: logging.StreamHandler
      formatter: simpleFormater
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    flogger:
      level: DEBUG
      handlers: [file]
    clogger:
      level: DEBUG
      handlers: [console]
  root:
    level: DEBUG
    handlers: [console, file]
